---
root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"

plugins:
  - "@typescript-eslint/eslint-plugin"

extends:
  - next/core-web-vitals
  # - eslint:recommended
  # - plugin:@typescript-eslint/eslint-recommended
  # - plugin:@typescript-eslint/recommended
  # - plugin:import/recommended

ignorePatterns:
  - ".eslintrc.*"
  - "*.config.js"

rules:
  "@next/next/no-img-element": off
